apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  generation
spec:
  prefix: /api/ticket/generate
  service: ticket-generation-service-app
  rewrite: ""
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  admin
spec:
  prefix: /api/ticket/count
  service: ticket-admin-service-app
  rewrite: ""
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  validation
spec:
  prefix: /api/ticket/validate
  service: ticket-validation-service-app
  rewrite: ""
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  invalidation
spec:
  prefix: /api/ticket/invalidate
  service: ticket-admin-service-app
  rewrite: ""