apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: ticket-admin-service-app
spec:
  selector:
    matchLabels:
      app: ticket-admin-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ticket-admin-service-app
    spec:
      containers:
      - name: ticket-admin-service-app
        image: lukascollishaw/ticketadminservice:1.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: server
        env:
        - name: Couchbase__Username
          valueFrom:
            secretKeyRef:
              name: cb-lwapi-auth
              key: username
        - name: Couchbase__Password
          valueFrom:
            secretKeyRef:
              name: cb-lwapi-auth
              key: password
        - name: Couchbase__ConnectionString
          value: couchbase://cb-lwapi-srv
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi